version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - api-mongo 
  api:
    container_name: ip-lookup
    build: 
      context: .
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://mongo:27017/ip
    networks:
      - api-mongo

networks:
  api-mongo:
    driver: bridge
